openapi: 3.0.1

info:
  title: Authors Haven API Documentation
  description: Create a community of like minded authors to foster inspiration and innovation by leveraging the modern web.
  version: 1.0.0
  contact:
    email: teamrambo50@gmail.com

license:
  name: Apache 2.0
  url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: /
    desription: Localhost server
  - url: https://authors-haven-development.herokuapp.com/
    desription: Heroku development server

paths:
  /:
    summary: Represent root of the application
    description: Represent root of the application.
    get:
      summary: Returns a welcome message.
      description: Returns a welcome message.
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
                example: Welcome to Authors Haven
  /api/v1/users/create:
    post:
      summary: Route for signing new users up
      description: Allow new users to register to use the application on providing valid details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/UserSignUp'
        description: user to be created
      responses:
        201:
          description: new user created successfully
        409:
          description: Conflict. Email or username exists
        500:
          description: Internal server error
  /api/v1/sessions/create:
    post:
      summary: Login Route
      description: Allow existing users to login to use the application
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - email
              - password
              properties:
                userLogin:
                  type: string
                  minLength: 6
                  example: JhayXXX
                password:
                  type: string
                  minLength: 8
                  example: incorrect
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/loginResponse"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponse"
        403:
          description: Incorrect username or password
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponse"
        500:
          description: Server Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/serverResponse"
  /api/v1/auth/facebook:
    get:
      summary: Route for signing new using facebook
      description: Allow new user to Login using facebook
      responses:
        302:
          description: redirect url
  /api/v1/auth/facebook/callback:
    get:
      summary: redirect url for facebook login/signup
      description: Allow existing users to signup or login
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                "$ref": "#/components/SocialUserSignUp"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SocialserverResponse"

  /api/v1/auth/google:
    get:
      summary: Route for signing new using google
      description: Allow new user to Login using google
      responses:
        302:
          description: redirect url
  /api/v1/auth/google/callback:
    get:
      summary: redirect url for google login/signup
      description: Allow existing users to signup or login
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                "$ref": "#/components/SocialUserSignUp"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SocialserverResponse"

  /api/v1/auth/twitter:
    get:
      summary: Route for signing new using twitter
      description: Allow new user to Login using twitter
      responses:
        302:
          description: redirect url
  /api/v1/auth/twitter/callback:
    get:
      summary: redirect url for twitter login/signup
      description: Allow existing users to signup or login
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                "$ref": "#/components/SocialUserSignUp"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SocialserverResponse"
  /api/v1/users/verifyEmail/{token}:
    get:
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          description: The token sent to the user's email for verification
      summary: Route for verifying emails
      description: Allow registered users to verify their emails
      responses:
        200:
          description: Success. Email verification was successful
        500:
          description: Internal server errorcomponents                
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  UserSignUp:
    type: object
    required:
    - firstName
    - lastName
    - userName
    - email
    - password
    properties:
      firstName:
        type: string
        example: Rihanna
      lastName:
        type: string
        example: Adeyemo
      userName:
        type: string
        example: RiriAde
      email:
        type: string
        example: riri.adeyemo@andela.com
      password:
        type: string
        example: incorrect
      confirmPassword:
        type: string
        example: incorrect
  SocialUserSignUp:
    type: object
    required:
    - firstName
    - lastName
    - userName
    - email
    - password
    - token
    properties:
      id:
        type: string
        example: 1
      firstName:
        type: string
        example: Adekay
      lastName:
        type: string
        example: Ade
      userName:
        type: string
        example: korey
      email:
        type: string
        example: riri.adeyemo@andela.com
      password:
        type: string
        example: incorrect
      confirmPassword:
        type: string
        example: incorrect
      token:
        type: string
        example: bhddmdmddddddddddddmddnddb
  schemas:
    loginResponse:
      type: object
      properties:
        user:
          type: object
        token:
          type: string
    errorResponse:
      type: object
      properties:
        message:
          type: string
    serverResponse:
      type: object
      properties:
        error:
          type: string
    SocialserverResponse:
      type: object
      properties:
        message:
          type: string
          example: Auth failed
    signoutResponse:
      type: object
      properties:
        message:
          type: string


